camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    filter:
      create: All Tasks
    authorization:
      enabled: false

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://n7qmaptgs6baip9z.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/sd104zmnv09fsqm0
    username: g65mtwvif31z21d8
    password: qjeu52xomwxxzd6o
    max-active: 2

database:
  connection: jdbc:mysql://g65mtwvif31z21d8:h30tstvleaybl3hd@n7qmaptgs6baip9z.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/sd104zmnv09fsqm0

mail:
  server: smtp.mailtrap.io
  username: f1854b4a218597
  password: 253400f50c8907
  sender: transgenic.lab@fhnw.ch
  